#!/bin/bash
# 🔗 URLs Rapides pour Tester l'Intégration

echo "🌐 URLs DE TEST - Intégration Trafic Abidjan"
echo "=============================================="
echo ""

# Déterminer le port (par défaut 8000)
PORT=${1:-8000}
HOST="localhost"
URL_BASE="http://$HOST:$PORT"

echo "📌 Configuration:"
echo "   Host: $HOST"
echo "   Port: $PORT"
echo "   Base URL: $URL_BASE"
echo ""

echo "🗺️ APPLICATION PRINCIPALE"
echo "========================"
echo ""
echo "1. Carte avec intégration trafic complète:"
echo "   🔗 $URL_BASE/map"
echo "   📝 Instructions:"
echo "      • Cliquer 'Filtres' (bouton en bas)"
echo "      • Cliquer une localité (Plateau, Cocody, etc.)"
echo "      • Voir trafic s'afficher"
echo "      • Cliquer segment pour pop-up"
echo ""

echo "🧪 PAGE DE TEST AUTONOME"
echo "======================="
echo ""
echo "2. Interface de test dédiée (sans authentification):"
echo "   🔗 $URL_BASE/test-traffic-integration.html"
echo "   📝 Avantages:"
echo "      • Pas besoin de login"
echo "      • Interface dédiée"
echo "      • Parfait pour debugging"
echo "      • Rapide et simple"
echo ""

echo "🔌 API DIRECTES"
echo "==============="
echo ""
echo "3. Tester API Plateau:"
echo "   curl \"$URL_BASE/api/traffic/flow?latitude=5.3391&longitude=-4.0329\""
echo ""
echo "4. Tester API Cocody:"
echo "   curl \"$URL_BASE/api/traffic/flow?latitude=5.3698&longitude=-4.0036\""
echo ""
echo "5. Tester API Yopougon:"
echo "   curl \"$URL_BASE/api/traffic/flow?latitude=5.3451&longitude=-4.1093\""
echo ""
echo "6. Tester API Abobo:"
echo "   curl \"$URL_BASE/api/traffic/flow?latitude=5.4294&longitude=-4.0089\""
echo ""
echo "7. Tester API Attécoubé:"
echo "   curl \"$URL_BASE/api/traffic/flow?latitude=5.3071&longitude=-4.0382\""
echo ""
echo "8. Tester API Marcory:"
echo "   curl \"$URL_BASE/api/traffic/flow?latitude=5.3163&longitude=-4.0063\""
echo ""

echo "📊 OUTILS DE DEBUG"
echo "=================="
echo ""
echo "9. Voir routes (grep traffic):"
echo "   php artisan route:list | grep traffic"
echo ""
echo "10. Voir logs en temps réel:"
echo "    tail -f storage/logs/laravel.log"
echo ""
echo "11. Ouvrir console navigateur:"
echo "    F12 → Console"
echo ""
echo "12. Vérifier Network (requêtes API):"
echo "    F12 → Network → Charger page → Voir requêtes"
echo ""

echo "📚 DOCUMENTATION"
echo "================"
echo ""
echo "13. Documentation technique:"
echo "    Voir: TRAFFIC_INTEGRATION.md"
echo ""
echo "14. Guide démarrage rapide:"
echo "    Voir: QUICKSTART_TRAFFIC.md"
echo ""
echo "15. Checklist production:"
echo "    Voir: TRAFFIC_DEPLOYMENT_CHECKLIST.md"
echo ""
echo "16. Résumé intégration:"
echo "    Voir: INTEGRATION_SUMMARY.md"
echo ""

echo "✅ VÉRIFICATION"
echo "=============="
echo ""
echo "17. Vérifier installation:"
echo "    bash verify-traffic-integration.sh"
echo ""

echo "🎯 COMMANDES UTILES"
echo "===================="
echo ""
echo "Démarrer serveur:"
echo "  php artisan serve"
echo ""
echo "Watcher assets:"
echo "  npm run watch"
echo ""
echo "Compiler production:"
echo "  npm run build"
echo ""
echo "Nettoyer cache:"
echo "  php artisan config:clear && php artisan cache:clear"
echo ""

echo "💡 TIPS"
echo "======"
echo ""
echo "• Pour tester rapidement: aller à $URL_BASE/test-traffic-integration.html"
echo "• Pour vérifier API: utiliser les commandes curl ci-dessus"
echo "• Pour déboguer: F12 → Console → voir erreurs/logs"
echo "• Pour voir données API: Network → traffic/flow → Response"
echo "• Pas de données? Vérifier TomTom API key dans .env"
echo ""

echo "🎉 C'est prêt à tester!"
echo ""
